[project]
name = "copyright-hook"
version = "0.1.0"
requires-python = ">=3.9"

[project.scripts]
copyright = "hooks.copyright:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

